on: [watch]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: 'treba.ml'
          port: '1522'
          ssh_private_key: ${{ secrets.SSH_RPI3 }} 
          local_path: './timetable.yml'
          remote_path: '/home/pirate/tg-timetable-bot/'
          args: '-o ConnectTimeout=5'
